language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev

script:
    - bin/atoum -d tests/units
    
    
notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
