language: php

dist: trusty
sudo: required

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - git clone --branch trusty --depth=1 https://github.com/rezzza/travis-ci.git ~/.rezzza.travis-ci
    - ~/.rezzza.travis-ci/php/bootstrap.sh apcu
    - phpenv rehash
    - composer install --optimize-autoloader --prefer-dist --no-scripts

script:
    - bin/atoum -d tests/units

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
